### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated.

### ISSUE THREAD

**Issue by rossjha** [offirgolan/ember-data-copyable#21]
Getting deprecation warnings for ember-cli-material-design-icons in Ember 3.x

> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

**Environment**

ember: 3.1.2
ember-cli: 3.1.4
ember-data-copyable: 0.3.2

**Comment by offirgolan** [comment]
This addon is already on ember-cli-babel ^6.6.0. The warning is probably coming from `ember-cli-material-design-icons`.

**Comment by rossjha** [comment]
OK thanks
