### ISSUE TITLE
indirect nested models not copied

### ISSUE THREAD

**Issue by BnitoBzh** [offirgolan/ember-data-copyable#24]
I have models like these :

Model page (Copyable without copyableOptions)
Model article (Copyable without copyableOptions)
Model media (Copyable without copyableOptions)
Model image (Copyable without copyableOptions)

page -> hasMany article -> belongsTo media -> belongsTo image.
page -> belongsTo media

When a page is copied its direct articles and media are copied too, but nested media (and there nested images) from articles aren't.

My copy's call :

```javascript
return this.get('page').copy(true, {
  relationships: {
    media: {
      deep: true,
      copyByReference: ['image'],
    },
    articles: {
      deep: true,
      relationships: {
        media: {
          deep: true,
          copyByReference: ['image']
        }
      }
    }
  }
}).then(copy => this.get('duplicateAction')(copy));
```

I am on ember-cli@3.4.3 / ember-data@3.4.2 / ember-souce@3.4.4

**Comment by BnitoBzh** [comment]
Closed.
After creating an issue test app i found the error. 
It comes from ember-data-changer-tracker addon because it does not mark a belongsTo relationship as changed, when it comes from a parent's copy. (something like this).

**Comment by rwwagner90** [comment]
@BnitoBzh how did you work around this? I think I may be seeing a similar issue.
