### ISSUE TITLE
Allow specifying a list of custom attributes to copy

### ISSUE THREAD

**Issue by leondmello** [offirgolan/ember-data-copyable#8]
When you copy a model which has custom attributes set on it, the custom attributes aren't copied.
Can there be an option which specifies which custom attributes to copy from the source model.

**Comment by offirgolan** [comment]
@leondmello yeah that should be pretty easy to add. I'll see what I can do in the next week or so.

**Comment by leondmello** [comment]
You can point me to where the change will be and I cant try to add it if you are busy
